# Generated by Django 4.2.14 on 2024-08-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edate', models.DateField()),
                ('issued_to', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'expenditure',
            },
        ),
    ]
